version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_blog:/var/lib/postgresql/data/
    env_file:
      - ./database/.env
    ports:
      - 5432:5432 

  blog:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery --app manage.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - blog
      - redis

  redis:
    image: redis:6-alpine

volumes:
  postgres_blog:
